/**
 * svgexport.js — production cutting-file generation (§7–8 of the brief).
 *
 * Emits real-world-unit SVG (width/height in mm, viewBox 1 unit = 1 mm),
 * which Cricut Design Space, Silhouette Studio, Inkscape and laser tools all
 * understand. Cut lines live in a `cut` group; human-readable labels live in
 * a separate `labels` group so they can be hidden/removed before cutting.
 *
 * This module is deliberately machine-agnostic: Cricut is one output target,
 * not an architectural dependency.
 */

import { pathBBox, r2 } from './geometry.js';

const XMLNS = 'http://www.w3.org/2000/svg';

function esc(s) {
  return String(s).replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

/**
 * Production piece: { label, pathMm, scale, mirror, seamAllowanceMm }
 * Placement (from nest.js): { xMm, yMm, wMm, hMm, rotated }
 *
 * Builds one cutting sheet for one material.
 * `materialName` appears in the sheet header label.
 */
export function buildCuttingSheetSVG({ pieces, placements, sheetWMm, usedHMm, materialName = 'Material' }) {
  const byId = new Map(pieces.map((p) => [p.id, p]));
  const cut = [];
  const labels = [];

  for (const pl of placements) {
    const p = byId.get(pl.id);
    if (!p) continue;
    const bb = pathBBox(p.pathMm);
    const s = p.scale ?? 1;
    // Base orientation transform: move the (scaled, possibly mirrored) piece
    // so its bbox top-left sits at the placement slot, honoring 90° rotation.
    const t = [];
    t.push(`translate(${r2(pl.xMm)} ${r2(pl.yMm)})`);
    if (pl.rotated) {
      // rotate 90° clockwise about origin, then shift into the slot
      t.push(`translate(${r2(pl.wMm)} 0) rotate(90)`);
    }
    t.push(`scale(${r2(p.mirror ? -s : s)} ${r2(s)})`);
    // after mirroring, bbox flips horizontally
    const bx = p.mirror ? -(bb.x + bb.w) : bb.x;
    t.push(`translate(${r2(-bx)} ${r2(-bb.y)})`);

    cut.push(`    <path d="${esc(p.pathMm)}" transform="${t.join(' ')}"/>`);
    labels.push(
      `    <text x="${r2(pl.xMm + pl.wMm / 2)}" y="${r2(pl.yMm + pl.hMm / 2)}" ` +
      `text-anchor="middle" dominant-baseline="middle" font-size="6">${esc(p.label)}</text>`
    );
    if (p.seamAllowanceMm) {
      // Approximate seam allowance: a second, uniformly outset cut line.
      // (True polygon offsetting is a post-MVP upgrade; the approximation is
      // labeled as such in the sheet.)
      const grow = 1 + (2 * p.seamAllowanceMm) / Math.max(bb.w * s, 1);
      const cx = bb.x + bb.w / 2, cy = bb.y + bb.h / 2;
      const t2 = t.slice(0, t.length - 1);
      t2.push(`translate(${r2(-bx)} ${r2(-bb.y)})`);
      t2.push(`translate(${r2(cx)} ${r2(cy)}) scale(${r2(grow)}) translate(${r2(-cx)} ${r2(-cy)})`);
      cut.push(`    <path d="${esc(p.pathMm)}" transform="${t2.join(' ')}" stroke-dasharray="2 2"/>`);
    }
  }

  const w = r2(sheetWMm), h = r2(Math.max(usedHMm, 10));
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="${XMLNS}" width="${w}mm" height="${h}mm" viewBox="0 0 ${w} ${h}">
  <title>${esc(materialName)} — cutting sheet</title>
  <desc>Generated by ReStitch. 1 unit = 1 mm. Cut the solid paths in the "cut" group; the "labels" group is informational only.</desc>
  <g id="cut" fill="none" stroke="#000" stroke-width="0.35">
${cut.join('\n')}
  </g>
  <g id="labels" fill="#888" font-family="sans-serif">
${labels.join('\n')}
  </g>
</svg>
`;
}

/**
 * Single-piece SVG (one component, true size) — handy for hand-cut
 * printable templates or importing individual shapes into cutter software.
 */
export function buildPieceSVG({ label, pathMm, scale = 1, mirror = false }) {
  const bb = pathBBox(pathMm);
  const w = r2(bb.w * scale), h = r2(bb.h * scale);
  const bx = mirror ? -(bb.x + bb.w) : bb.x;
  const transform =
    `scale(${r2(mirror ? -scale : scale)} ${r2(scale)}) translate(${r2(-bx)} ${r2(-bb.y)})`;
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="${XMLNS}" width="${w}mm" height="${h}mm" viewBox="0 0 ${w} ${h}">
  <title>${esc(label)}</title>
  <g fill="none" stroke="#000" stroke-width="0.35">
    <path d="${esc(pathMm)}" transform="${transform}"/>
  </g>
</svg>
`;
}
